### ISSUE TITLE
User's Default Lists (return a user's lists)

### ISSUE THREAD

**Issue by KelsiePorter** [Streamlined-Turing/streamlined_be#16]
Endpoints for User's 3 default lists 

- Currently Watching
- Want To Watch
- Watched

- [x]  Route with query params `/api/v1/users/:user_id/lists?list=<list_name>`
- [x]  Index (dynamically return single lists given list params)

**Comment by Pocketzs** [comment]
Only thing left if documenting the pull request with response snippets and endpoint explanations
